services:
  qr:
    image: localhost:5000/qr:latest
    container_name: qr
    restart: unless-stopped
    ports:
      - "7003:7003"
    networks:
      - proxy
      - internal
    volumes:
      - qr-images:/app/static
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  qr-images:

networks:
  proxy:
    external: true
  internal:
    external: true
