package main

import (
	"fmt"
	"html/template"
	"log"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/yeqown/go-qrcode/v2"
	"github.com/yeqown/go-qrcode/writer/standard"
)

const IMAGE_NAME = "imgName"
const STATIC_DIR = "static"
const MAX_INPUT_LENGTH = 2048
const MAX_BODY_SIZE = 4096

type PageData struct {
	ImageURL string
	Error    string
}

var ImageOptions []standard.ImageOption = []standard.ImageOption{
	standard.WithBgColorRGBHex("#0F1822"),
	standard.WithFgColorRGBHex("#DDE61F"),
}

func main() {
	mux := http.NewServeMux()
	cleanupTick := time.NewTicker(5 * time.Minute)

	fileServerDir := fmt.Sprintf("./%s", STATIC_DIR)
	fileServerPattern := fmt.Sprintf("GET /%s/", STATIC_DIR)
	fileServerStrip := fmt.Sprintf("/%s/", STATIC_DIR)

	fs := http.FileServer(http.Dir(fileServerDir))
	mux.Handle(fileServerPattern, http.StripPrefix(fileServerStrip, fs))

	mux.HandleFunc("GET /", func(w http.ResponseWriter, r *http.Request) {
		t, err := template.New("index.html").ParseFiles("templates/layout.html", "templates/index.html")
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		data := PageData{}
		err = t.ExecuteTemplate(w, "layout", data)
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
	})

	mux.HandleFunc("GET /{imgName}", func(w http.ResponseWriter, r *http.Request) {
		q := r.PathValue(IMAGE_NAME)

		// Validate imgName is a valid UUID to prevent path traversal.
		if _, err := uuid.Parse(q); err != nil {
			renderWithError(w, "QR code not found or has expired")
			return
		}

		filePath := fmt.Sprintf("%s/%s.png", STATIC_DIR, q)

		if _, err := os.Stat(filePath); os.IsNotExist(err) {
			renderWithError(w, "QR code not found or has expired")
			return
		}

		t, err := template.New("index.html").ParseFiles("templates/layout.html", "templates/index.html")
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		data := PageData{ImageURL: filePath}
		err = t.ExecuteTemplate(w, "layout", data)
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
	})

	mux.HandleFunc("POST /generate", func(w http.ResponseWriter, r *http.Request) {
		r.Body = http.MaxBytesReader(w, r.Body, MAX_BODY_SIZE)
		text := r.FormValue("string")

		if text == "" {
			renderWithError(w, "Please enter text to generate QR code")
			return
		}

		if len(text) > MAX_INPUT_LENGTH {
			renderWithError(w, "Input text is too long")
			return
		}

		qrc, err := qrcode.New(text)
		if err != nil {
			log.Printf("QR generation error: %v", err)
			renderWithError(w, "Could not generate QR code")
			return
		}
		id := uuid.New()
		filePath := fmt.Sprintf("%s/%s.png", STATIC_DIR, id.String())
		wr, err := standard.New(filePath, ImageOptions...)
		if err != nil {
			log.Printf("Image file creation error: %v", err)
			renderWithError(w, "Could not create image file")
			return
		}
		if err = qrc.Save(wr); err != nil {
			log.Printf("Image save error: %v", err)
			renderWithError(w, "Could not save image")
			return
		}
		redirectUrl := fmt.Sprintf("/%s", id.String())
		http.Redirect(w, r, redirectUrl, http.StatusFound)
	})

	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		log.Printf("Server starting on port 7003")
		if err := http.ListenAndServe(":7003", mux); err != nil {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	go func() {
		for range cleanupTick.C {
			cleanupImages()
		}
	}()

	wg.Wait()
}

func renderWithError(w http.ResponseWriter, errorMsg string) {
	t, err := template.New("index.html").ParseFiles("templates/layout.html", "templates/index.html")
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	data := PageData{Error: errorMsg}
	err = t.ExecuteTemplate(w, "layout", data)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
}

func cleanupImages() {
	dir, err := os.ReadDir(STATIC_DIR)
	if err != nil {
		log.Printf("error reading static dir for cleanup: %v", err)
		return
	}
	var count int
	for _, entry := range dir {
		if entry.IsDir() {
			continue
		}
		// Only clean up .png files generated by us.
		name := entry.Name()
		if len(name) < 4 || name[len(name)-4:] != ".png" {
			continue
		}
		fileName := fmt.Sprintf("%s/%s", STATIC_DIR, name)
		if err := os.Remove(fileName); err != nil {
			log.Printf("error cleaning up file: %s", fileName)
		} else {
			count++
		}
	}
	if count > 0 {
		log.Printf("Cleanup: removed %d QR image(s)", count)
	}
}
